/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateUserInput = {
  id?: string | null,
  name?: string | null,
  imageUri?: string | null,
  snils?: string | null,
  about?: string | null,
  phone: string,
  website?: string | null,
  email: string,
  competence?: Array< string | null > | null,
  company?: string | null,
  position?: string | null,
  startDateWork?: string | null,
  endDateWork?: string | null,
  responsibilities?: Array< string | null > | null,
  studyPlace?: string | null,
  specialization?: string | null,
  degree?: string | null,
  startDateStudy?: string | null,
  endDateStudy?: string | null,
  project?: string | null,
};

export type ModelUserConditionInput = {
  name?: ModelStringInput | null,
  imageUri?: ModelStringInput | null,
  snils?: ModelStringInput | null,
  about?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  website?: ModelStringInput | null,
  email?: ModelStringInput | null,
  competence?: ModelStringInput | null,
  company?: ModelStringInput | null,
  position?: ModelStringInput | null,
  startDateWork?: ModelStringInput | null,
  endDateWork?: ModelStringInput | null,
  responsibilities?: ModelStringInput | null,
  studyPlace?: ModelStringInput | null,
  specialization?: ModelStringInput | null,
  degree?: ModelStringInput | null,
  startDateStudy?: ModelStringInput | null,
  endDateStudy?: ModelStringInput | null,
  project?: ModelStringInput | null,
  and?: Array< ModelUserConditionInput | null > | null,
  or?: Array< ModelUserConditionInput | null > | null,
  not?: ModelUserConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type User = {
  __typename: "User",
  id: string,
  name?: string | null,
  imageUri?: string | null,
  snils?: string | null,
  about?: string | null,
  phone: string,
  website?: string | null,
  email: string,
  competence?: Array< string | null > | null,
  company?: string | null,
  position?: string | null,
  startDateWork?: string | null,
  endDateWork?: string | null,
  responsibilities?: Array< string | null > | null,
  studyPlace?: string | null,
  specialization?: string | null,
  degree?: string | null,
  startDateStudy?: string | null,
  endDateStudy?: string | null,
  project?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateUserInput = {
  id: string,
  name?: string | null,
  imageUri?: string | null,
  snils?: string | null,
  about?: string | null,
  phone?: string | null,
  website?: string | null,
  email?: string | null,
  competence?: Array< string | null > | null,
  company?: string | null,
  position?: string | null,
  startDateWork?: string | null,
  endDateWork?: string | null,
  responsibilities?: Array< string | null > | null,
  studyPlace?: string | null,
  specialization?: string | null,
  degree?: string | null,
  startDateStudy?: string | null,
  endDateStudy?: string | null,
  project?: string | null,
};

export type DeleteUserInput = {
  id: string,
};

export type CreateProjectInput = {
  id?: string | null,
  branch: string,
  author: string,
  name: string,
  imageUri?: string | null,
  FIO: string,
  phone: string,
  email: string,
  team?: Array< string | null > | null,
  description?: string | null,
  advantage?: string | null,
  stage?: string | null,
  intellect?: string | null,
  problem?: string | null,
  marketUsage?: string | null,
  consumers?: string | null,
  competitors?: string | null,
  launchDate?: string | null,
  experience?: string | null,
  resources?: string | null,
  currentState?: string | null,
  model?: string | null,
  plan?: string | null,
};

export type ModelProjectConditionInput = {
  branch?: ModelStringInput | null,
  author?: ModelStringInput | null,
  name?: ModelStringInput | null,
  imageUri?: ModelStringInput | null,
  FIO?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  team?: ModelStringInput | null,
  description?: ModelStringInput | null,
  advantage?: ModelStringInput | null,
  stage?: ModelStringInput | null,
  intellect?: ModelStringInput | null,
  problem?: ModelStringInput | null,
  marketUsage?: ModelStringInput | null,
  consumers?: ModelStringInput | null,
  competitors?: ModelStringInput | null,
  launchDate?: ModelStringInput | null,
  experience?: ModelStringInput | null,
  resources?: ModelStringInput | null,
  currentState?: ModelStringInput | null,
  model?: ModelStringInput | null,
  plan?: ModelStringInput | null,
  and?: Array< ModelProjectConditionInput | null > | null,
  or?: Array< ModelProjectConditionInput | null > | null,
  not?: ModelProjectConditionInput | null,
};

export type Project = {
  __typename: "Project",
  id: string,
  branch: string,
  author: string,
  name: string,
  imageUri?: string | null,
  FIO: string,
  phone: string,
  email: string,
  team?: Array< string | null > | null,
  description?: string | null,
  advantage?: string | null,
  stage?: string | null,
  intellect?: string | null,
  problem?: string | null,
  marketUsage?: string | null,
  consumers?: string | null,
  competitors?: string | null,
  launchDate?: string | null,
  experience?: string | null,
  resources?: string | null,
  currentState?: string | null,
  model?: string | null,
  plan?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateProjectInput = {
  id: string,
  branch?: string | null,
  author?: string | null,
  name?: string | null,
  imageUri?: string | null,
  FIO?: string | null,
  phone?: string | null,
  email?: string | null,
  team?: Array< string | null > | null,
  description?: string | null,
  advantage?: string | null,
  stage?: string | null,
  intellect?: string | null,
  problem?: string | null,
  marketUsage?: string | null,
  consumers?: string | null,
  competitors?: string | null,
  launchDate?: string | null,
  experience?: string | null,
  resources?: string | null,
  currentState?: string | null,
  model?: string | null,
  plan?: string | null,
};

export type DeleteProjectInput = {
  id: string,
};

export type ModelUserFilterInput = {
  id?: ModelIDInput | null,
  name?: ModelStringInput | null,
  imageUri?: ModelStringInput | null,
  snils?: ModelStringInput | null,
  about?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  website?: ModelStringInput | null,
  email?: ModelStringInput | null,
  competence?: ModelStringInput | null,
  company?: ModelStringInput | null,
  position?: ModelStringInput | null,
  startDateWork?: ModelStringInput | null,
  endDateWork?: ModelStringInput | null,
  responsibilities?: ModelStringInput | null,
  studyPlace?: ModelStringInput | null,
  specialization?: ModelStringInput | null,
  degree?: ModelStringInput | null,
  startDateStudy?: ModelStringInput | null,
  endDateStudy?: ModelStringInput | null,
  project?: ModelStringInput | null,
  and?: Array< ModelUserFilterInput | null > | null,
  or?: Array< ModelUserFilterInput | null > | null,
  not?: ModelUserFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelUserConnection = {
  __typename: "ModelUserConnection",
  items?:  Array<User | null > | null,
  nextToken?: string | null,
};

export type ModelProjectFilterInput = {
  id?: ModelIDInput | null,
  branch?: ModelStringInput | null,
  author?: ModelStringInput | null,
  name?: ModelStringInput | null,
  imageUri?: ModelStringInput | null,
  FIO?: ModelStringInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  team?: ModelStringInput | null,
  description?: ModelStringInput | null,
  advantage?: ModelStringInput | null,
  stage?: ModelStringInput | null,
  intellect?: ModelStringInput | null,
  problem?: ModelStringInput | null,
  marketUsage?: ModelStringInput | null,
  consumers?: ModelStringInput | null,
  competitors?: ModelStringInput | null,
  launchDate?: ModelStringInput | null,
  experience?: ModelStringInput | null,
  resources?: ModelStringInput | null,
  currentState?: ModelStringInput | null,
  model?: ModelStringInput | null,
  plan?: ModelStringInput | null,
  and?: Array< ModelProjectFilterInput | null > | null,
  or?: Array< ModelProjectFilterInput | null > | null,
  not?: ModelProjectFilterInput | null,
};

export type ModelProjectConnection = {
  __typename: "ModelProjectConnection",
  items?:  Array<Project | null > | null,
  nextToken?: string | null,
};

export type CreateUserMutationVariables = {
  input: CreateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type CreateUserMutation = {
  createUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateUserMutationVariables = {
  input: UpdateUserInput,
  condition?: ModelUserConditionInput | null,
};

export type UpdateUserMutation = {
  updateUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteUserMutationVariables = {
  input: DeleteUserInput,
  condition?: ModelUserConditionInput | null,
};

export type DeleteUserMutation = {
  deleteUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateProjectMutationVariables = {
  input: CreateProjectInput,
  condition?: ModelProjectConditionInput | null,
};

export type CreateProjectMutation = {
  createProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateProjectMutationVariables = {
  input: UpdateProjectInput,
  condition?: ModelProjectConditionInput | null,
};

export type UpdateProjectMutation = {
  updateProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteProjectMutationVariables = {
  input: DeleteProjectInput,
  condition?: ModelProjectConditionInput | null,
};

export type DeleteProjectMutation = {
  deleteProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetUserQueryVariables = {
  id: string,
};

export type GetUserQuery = {
  getUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListUsersQueryVariables = {
  filter?: ModelUserFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListUsersQuery = {
  listUsers?:  {
    __typename: "ModelUserConnection",
    items?:  Array< {
      __typename: "User",
      id: string,
      name?: string | null,
      imageUri?: string | null,
      snils?: string | null,
      about?: string | null,
      phone: string,
      website?: string | null,
      email: string,
      competence?: Array< string | null > | null,
      company?: string | null,
      position?: string | null,
      startDateWork?: string | null,
      endDateWork?: string | null,
      responsibilities?: Array< string | null > | null,
      studyPlace?: string | null,
      specialization?: string | null,
      degree?: string | null,
      startDateStudy?: string | null,
      endDateStudy?: string | null,
      project?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type GetProjectQueryVariables = {
  id: string,
};

export type GetProjectQuery = {
  getProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListProjectsQueryVariables = {
  filter?: ModelProjectFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListProjectsQuery = {
  listProjects?:  {
    __typename: "ModelProjectConnection",
    items?:  Array< {
      __typename: "Project",
      id: string,
      branch: string,
      author: string,
      name: string,
      imageUri?: string | null,
      FIO: string,
      phone: string,
      email: string,
      team?: Array< string | null > | null,
      description?: string | null,
      advantage?: string | null,
      stage?: string | null,
      intellect?: string | null,
      problem?: string | null,
      marketUsage?: string | null,
      consumers?: string | null,
      competitors?: string | null,
      launchDate?: string | null,
      experience?: string | null,
      resources?: string | null,
      currentState?: string | null,
      model?: string | null,
      plan?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateUserSubscription = {
  onCreateUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateUserSubscription = {
  onUpdateUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteUserSubscription = {
  onDeleteUser?:  {
    __typename: "User",
    id: string,
    name?: string | null,
    imageUri?: string | null,
    snils?: string | null,
    about?: string | null,
    phone: string,
    website?: string | null,
    email: string,
    competence?: Array< string | null > | null,
    company?: string | null,
    position?: string | null,
    startDateWork?: string | null,
    endDateWork?: string | null,
    responsibilities?: Array< string | null > | null,
    studyPlace?: string | null,
    specialization?: string | null,
    degree?: string | null,
    startDateStudy?: string | null,
    endDateStudy?: string | null,
    project?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateProjectSubscription = {
  onCreateProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateProjectSubscription = {
  onUpdateProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteProjectSubscription = {
  onDeleteProject?:  {
    __typename: "Project",
    id: string,
    branch: string,
    author: string,
    name: string,
    imageUri?: string | null,
    FIO: string,
    phone: string,
    email: string,
    team?: Array< string | null > | null,
    description?: string | null,
    advantage?: string | null,
    stage?: string | null,
    intellect?: string | null,
    problem?: string | null,
    marketUsage?: string | null,
    consumers?: string | null,
    competitors?: string | null,
    launchDate?: string | null,
    experience?: string | null,
    resources?: string | null,
    currentState?: string | null,
    model?: string | null,
    plan?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
