/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://lisxb6fvingvbmbv3ilfyt6ywu.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tcw5crapzzcyfg7oz5ty7blg24",
    "aws_cognito_identity_pool_id": "eu-central-1:f86c5e91-a34b-4661-93eb-08c7161fe47a",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_cKCotwrPh",
    "aws_user_pools_web_client_id": "5pt5mhcrnedfcr1hop7qjk6k4n",
    "oauth": {}
};


export default awsmobile;
